### PR TITLE
Some changes for knitro 10.0

### PR DESCRIPTION
**Pull request by yeesian**
- introduced (but untested) `set_linearvars` and `set_honorbnds`
- bugfixes for (unexported) `addcompcons` and `chgvarbnds`
- simplified version of `get_param`
- updated parameter list
- `KTR_RC_FEVAL_LIMIT` seems to have been replaced with `KTR_RC_FEVAL_LIMIT_FEAS`
- update for MPB 0.4

### CODE REVIEW

**Comment by yeesian** [comment]
I'm starting to regret exporting all those functions in `src/ktr_functions.jl` back then

**Comment by yeesian** [comment]
@mlubin

**Comment by mlubin** [comment]
LGTM. Everything passing?

**Comment by yeesian** [comment]
On julia v0.4, MPB 0.4, JuMP master, yup

**Comment by mlubin** [comment]
Cool! Feel free to tag. It should be v0.1.0 since we've dropped support for Julia 0.3.

**Pull request merged**
