### PR TITLE
Skip build and tests when calling package from Github Actions

### PR DESCRIPTION
**Pull request by frapac**

### CODE REVIEW

**Comment by frapac** [comment]
However, it seems that this solution is not working: 
https://github.com/JuliaRegistries/General/pull/6257

@odow did you have any follow up from the JuliaRegistries folks?

**Comment by odow** [comment]
No. This does not work. They never got back to me. Maybe we should ask on the slack channel?

**Comment by odow** [comment]
I might have a work-around. It looks like they install the `RegistryCI` package, which is only really needed for General, so
```Julia
if haskey(Pkg.installed(), "RegistryCI")
    # skip
end
```

**Comment by frapac** [comment]
Good catch. In any case, I think I will follow up our problem on the slack channel.

**Pull request closed without merging**
