### PR TITLE
Pass warmstarts as keyword arguments

### PR DESCRIPTION
**Pull request by yeesian**
**Warning**: it is a breaking change

- change warmstarts to keyword arguments,
- provide no-hessian initialization, and
- allow setting of individual callbacks

### CODE REVIEW

**Comment by mlubin** [comment]
Could you clarify what issue this is addressing? This is only breaking for users of the low-level interface, not MPB, correct?

**Comment by yeesian** [comment]
Yup, only breaking for users of the low-level interface, and not MPB.

It makes it easier to work with KNITRO's callback interface, since we currently [clump all of them up](https://github.com/JuliaOpt/KNITRO.jl/blob/master/src/KNITRO.jl#L287-L297) in a single call to `setCallbacks()`.

It isn't yet a full solution, since there's a fairly careful coupling between setting parameters through `setOption()`, calling `initializeProblem()`, and `set*CallBack()`, but it goes a small way towards addressing concerns like https://github.com/JuliaOpt/KNITRO.jl/issues/25#issue-57121021.

**Comment by mlubin** [comment]
Ok, fine with me. Does it need docs updates?

**Comment by yeesian** [comment]
Existing documentation is still correct (not least for being a little vague 😛 ). I have added `examples/hs035_nohess.jl`, but am not enthusiastic about documenting the individual callbacks in this package's ReadTheDocs, since they are mostly workarounds for users who are unhappy with MPB/JuMP, and willing to look through the examples on their own. I'll be happy to take PRs from users who want to improve the state of this package's documentation though.

**Comment by mlubin** [comment]
Sounds good, just wanted to check that the docs weren't blatantly incorrect.

**Comment by yeesian** [comment]
I'll do a separate PR for the docs, since [they're dead](https://github.com/JuliaOpt/KNITRO.jl/issues/56) anyway.

**Pull request merged**
