### PR TITLE
Fixed test failures

### PR DESCRIPTION
**Pull request by gragusa**
When I Pkg.test("KNITRO") I gat a failed test. Specifically `hs035_restart.jl` tests

```
@test get_number_FC_evals(kp)==7
@test get_number_GA_evals(kp)==7
@test get_number_iters(kp) == 6
```
test fails because the correct values are 
```
@test get_number_FC_evals(kp)==6
@test get_number_GA_evals(kp)==6
@test get_number_iters(kp) == 5
```.

### CODE REVIEW

**Comment by gragusa** [comment]
However, even with these fixes,  the test requires `JuMP.jl` and one of the linear solver to be installed otherwise it fails. This test should probably be conditional on having `JuMP` and a linear solver installed.

**Comment by mlubin** [comment]
It seems like these numbers could vary across different platforms and KNITRO versions, I'm not sure if these tests are reasonable.
Also JuMP should be listed in ``test/REQUIRE``.

**Comment by gragusa** [comment]
Exactly. I tried testing KNITRO on another machine and the test passed
(JuMP availability still being an issue).

**Comment by yeesian** [comment]
Ah yeah, thanks for pointing it out! When starting out, I really meant to only test that they work, and not so much for their specific output values. Perhaps a more reasonable approach would be to change them to `println` statements. @gragusa, you can have a look at JuMP's `test/REQUIRE` ([here](https://github.com/JuliaOpt/JuMP.jl/blob/master/test/REQUIRE)) to see how to add `JuMP` to the list of test requirements

**Comment by gragusa** [comment]
Closing this. I will reopen a new one that adds REQUIRE and fixes the test failures.

**Pull request closed without merging**
