### PR TITLE
Enable resolve via the MathProgBase interface

### PR DESCRIPTION
**Pull request by davidanthoff**

### CODE REVIEW

**Comment by mlubin** [comment]
Thanks for this. @yeesian?

**Comment by yeesian** [comment]
yeah was checking if it works with #11. I thought there was a discussion regarding the delaying of the initialization to the call to ```optimize!``` but it seems to work fine now. Let me look into it abit?

**Comment by davidanthoff** [comment]
Please check that carefully. I don't understand the codebase, nor MathProgBase etc.

**Comment by yeesian** [comment]
It's been a while since I last touched the codebase, but I recall a discussion in https://github.com/JuliaOpt/JuMP.jl/pull/333, and I wrote the code when I was still new to the KNITRO API and JuMP/MPB (as my way of learning about them); I'm sorry if I'm taking longer than I should, haha

**Comment by mlubin** [comment]
I think we need to leave the call to ``KTR_init_problem`` inside of ``optimize``, but skip the call it if none of the input data (dimensions, variable type) have changed. I don't know what the knitro API says about how to reoptimize if the callbacks remain the same though.

**Comment by yeesian** [comment]
I don't know of any other way, apart from building a new model, with the modified parameters. I think the API (https://github.com/JuliaOpt/KNITRO.jl/blob/master/src/ktr_functions.jl) only allows you to change the variable's bounds so far

**Comment by yeesian** [comment]
> I think we need to leave the call to KTR_init_problem inside of optimize

I can't remember why though. From what I can see ([here](https://github.com/JuliaOpt/JuMP.jl/blob/47f75c144bc4594b295866db860cc85bef48b5ab/src/nlp.jl#L481-L498)), they are done in sequence, so each call to `solve` (and hence `solvenlp`) rebuilds a new model, before solving it anyway?

**Comment by yeesian** [comment]
@davidanthoff more concretely; here's an example where this PR fails:

```julia
using KNITRO, JuMP, FactCheck

## Solve test problem 1 (Synthesis of processing system) in
 #  M. Duran & I.E. Grossmann, "An outer approximation algorithm for
 #  a class of mixed integer nonlinear programs", Mathematical
 #  Programming 36, pp. 307-339, 1986.  The problem also appears as
 #  problem synthes1 in the MacMINLP test set.
 #
 #  min   5 x4 + 6 x5 + 8 x6 + 10 x1 - 7 x3 -18 math.log(x2 + 1)
 #       - 19.2 math.log(x1 - x2 + 1) + 10
 #  s.t.  0.8 math.log(x2 + 1) + 0.96 math.log(x1 - x2 + 1) - 0.8 x3 >= 0
 #        math.log(x2 + 1) + 1.2 math.log(x1 - x2 + 1) - x3 - 2 x6 >= -2
 #        x2 - x1 <= 0
 #        x2 - 2 x4 <= 0
 #        x1 - x2 - 2 x5 <= 0
 #        x4 + x5 <= 1
 #        0 <= x1 <= 2 
 #        0 <= x2 <= 2
 #        0 <= x3 <= 1
 #        x1, x2, x3 continuous
 #        x4, x5, x6 binary
 #        
 #
 #  The solution is (1.30098, 0, 1, 0, 1, 0).
 ##

m = Model(solver=KnitroSolver(mip_method = KTR_MIP_METHOD_BB,
                              algorithm = KTR_ALG_ACT_CG,
                              outmode = KTR_OUTMODE_SCREEN,
                              KTR_PARAM_OUTLEV = KTR_OUTLEV_ALL,
                              KTR_PARAM_MIP_OUTINTERVAL = 1,
                              KTR_PARAM_MIP_MAXNODES = 10000,
                              KTR_PARAM_HESSIAN_NO_F = KTR_HESSIAN_NO_F_ALLOW))
x_U = [2,2,1]
@defVar(m, x_U[i] >= x[i=1:3] >= 0)
@defVar(m, y[4:6], Bin)

@setNLObjective(m, Min, 10 + 10*x[1] - 7*x[3] + 5*y[4] + 6*y[5] + 8*y[6] - 18*log(x[2]+1) - 19.2*log(x[1]-x[2]+1))
@addNLConstraint(m, 0.8*log(x[2] + 1) + 0.96*log(x[1] - x[2] + 1) - 0.8*x[3] >= 0)
@addNLConstraint(m, log(x[2] + 1) + 1.2*log(x[1] - x[2] + 1) - x[3] - 2*y[6] >= -2)
@addNLConstraint(m, x[2] - x[1] <= 0)
@addNLConstraint(m, x[2] - 2*y[4] <= 0)
@addNLConstraint(m, x[1] - x[2] - 2*y[5] <= 0)
@addNLConstraint(m, y[4] + y[5] <= 1)
solve(m)
```

yields
```julia
julia> @fact [getValue(x)[:],getValue(y)[:]] => roughly([1.30098, 0.0, 1.0, 0.0, 1.0, 0.0], 1e-5)

Failure :: (line:366) :: got [1.14652,0.546596,1.0,0.273298,0.299959,0.0]
[(getValue(x))[:],(getValue(y))[:]] => roughly([1.30098,0.0,1.0,0.0,1.0,0.0],1.0e-5)
```

**Comment by davidanthoff** [comment]
What about this version?

@mlubin are you going to add the fact check on master to the test?

**Comment by yeesian** [comment]
There is a ```kp.inner.status``` flag. Can you try
```julia
function optimize!(m::KnitroMathProgModel)
    if applicationReturnStatus(m.inner) in (:Uninitialized, # New problem
                                            :Initialized)   # For MIP Problems through JuMP
        if all(x->x==KTR_VARTYPE_CONTINUOUS, m.varType)
            initializeProblem(m.inner, m.sense, m.objType, m.varLB, m.varUB, m.constrType,
                              m.constrLB, m.constrUB, m.jac_var, m.jac_con, m.hess_row, m.hess_col,
                              m.initial_x)
        else
            initializeProblem(m.inner, m.sense, m.objType, m.objFnType,
                              m.varType, m.varLB, m.varUB, m.constrType,
                              m.constrFnType, m.constrLB, m.constrUB,
                              m.jac_var, m.jac_con, m.hess_row, m.hess_col, m.initial_x)
        end
        solveProblem(m.inner)
    else
        warn("Problem has been solved with status $(applicationReturnStatus(m.inner)). Try restarting the problem?")
    end
end
```
instead?

**Comment by yeesian** [comment]
> are you going to add the fact check on master to the test?

My understanding (from [here]((https://github.com/JuliaOpt/KNITRO.jl/commit/0ac9531c1cbcd05c2bafbebcb52457c9859f1d61)) is to minimize code duplication in the tests between the solvers and JuMP. I usually just run the `jump_*.jl` in this repository for a quick check on any new changes.

A better way forward will be to link up with the tests in JuMP to check (the way it's done with MathProgBase [here](https://github.com/JuliaOpt/KNITRO.jl/blob/master/test/mathprogtest.jl)). But JuMP is not required for this package the way MathProgBase is, which makes it trickier.

**Comment by tkelman** [comment]
You can add JuMP to `test/REQUIRE` so it gets installed when you do `Pkg.test("KNITRO")` but isn't required to just use this package

**Comment by davidanthoff** [comment]
@yeesian, how about this version? It is slightly different than what you suggested. In particular, I don't want to throw a warning if ``optimize!`` is called repeatedly because that is just the scenario I'm trying to enable.

**Comment by yeesian** [comment]
That's fine with me. @mlubin?

**Comment by mlubin** [comment]
Seems alright. @davidanthoff, would you mind adding a small test to jump which checks that you can re-solve with an NLP solver? That's the best way to make sure all solvers support this.

**Comment by mlubin** [comment]
Actually we might already have one. I'm mobile but will check in a bit

**Comment by davidanthoff** [comment]
I don't think I had that problem when I tried to resolve with JuMP. I'm using MathProgBase directly.

**Comment by mlubin** [comment]
You could add a test [here](https://github.com/JuliaOpt/MathProgBase.jl/blob/44594bc505510a1ac214bf75215643a8c134f2f1/test/nlp.jl) then

**Comment by davidanthoff** [comment]
I now added some tests to MathProgBase that resolve NLP problems.

I also had to add some more stuff to this code. It seems one always has to call ``KTR_restart`` before a second ``KTR_init`` call.

**Comment by davidanthoff** [comment]
Oh, and I should add: the KNITRO documentation is unclear whether one really has to call ``KTR_restart`` before a second ``KTR_solve`` call. But, when I tried without ``KTR_restart`` I got a return value of ``5`` from ``KTR_solve``, which is actually not one of the documented return values... Adding the ``KTR_restart`` call solved the problem...

**Comment by mlubin** [comment]
Looks reasonable to me, let's go with it and see what happens. Could you squash the commits?

**Comment by davidanthoff** [comment]
All squashed.

**Pull request merged**
