### PR TITLE
Compatibility MathProgBase.eval_hesslag_prod

### PR DESCRIPTION
**Pull request by edljk**
See definition

[MathProgBase.eval_hesslag_prod](http://mathprogbasejl.readthedocs.io/en/latest/nlp.html#eval_hesslag_prod)

which was not compatible with 

`eval_hv_cb(x, lambda, sigma, hv) = eval_hesslag_prod(d, hv, x, sigma, lambda)`

### CODE REVIEW

**Comment by mlubin** [comment]
Could you add a test that fails with the original code and passes with your fix?

**Comment by edljk** [comment]
The following naive example produces the expected error and should be ok (?) with the small modification

````julia using MathProgBase, KNITRO
type Myquad <: MathProgBase.AbstractNLPEvaluator
end
MathProgBase.features_available(d::Myquad) = [:Grad,:HessVec]
function MathProgBase.initialize(d::Myquad,requested_features::Vector{Symbol})
    for feat in requested_features
        if !(feat in [:Grad,:Jac,:HessVec])
            error("Unsupported feature $feat")
        end
    end
end
MathProgBase.eval_g(d::Myquad,g,x) = nothing
MathProgBase.eval_jac_g(d::Myquad,g1,g2) = nothing
MathProgBase.jac_structure(d::Myquad) = Int64[], Int64[]
function MathProgBase.eval_f(d::Myquad, x)
    return x[1]^2+x[2]^2
end
function MathProgBase.eval_grad_f(d::Myquad, grad_f, x)
    grad_f[1] = 2*x[1]
    grad_f[2] = 2*x[2]
end
function MathProgBase.eval_hesslag_prod(d::Myquad,h,x,v,σ,μ)
    h[1] = 2*σ*v[1]
    h[2] = 2*σ*v[2]
end
m = MathProgBase.NonlinearModel(KnitroSolver(KTR_PARAM_OUTLEV=2,KTR_PARAM_HESSOPT=5))
MathProgBase.loadproblem!(m,2,0,-ones(2),ones(2),Float64[],Float64[],:Min,Myquad())
MathProgBase.setwarmstart!(m,rand(2)); MathProgBase.optimize!(m)````

`=======================================
          Commercial License
         Artelys Knitro 10.0.0
=======================================

Knitro presolve eliminated 0 variables and 0 constraints.

hessopt:              5
The problem is identified as bound constrained only.
Knitro changing algorithm from AUTO to 2.
Knitro changing bar_initpt from AUTO to 3.
Knitro changing bar_murule from AUTO to 1.
Knitro changing bar_penaltycons from AUTO to 1.
Knitro changing bar_penaltyrule from AUTO to 2.
Knitro changing bar_switchrule from AUTO to 1.
Knitro changing linsolver from AUTO to 4.

Problem Characteristics                    ( Presolved)
-----------------------
Objective goal:  Minimize
Number of variables:                     2 (         2)
    bounded below:                       0 (         0)
    bounded above:                       0 (         0)
    bounded below and above:             2 (         2)
    fixed:                               0 (         0)
    free:                                0 (         0)
Number of constraints:                   0 (         0)
    linear equalities:                   0 (         0)
    nonlinear equalities:                0 (         0)
    linear inequalities:                 0 (         0)
    nonlinear inequalities:              0 (         0)
    range:                               0 (         0)
Number of nonzeros in Jacobian:          0 (         0)
Number of nonzeros in Hessian:           0 (         0)

  Iter      Objective      FeasError   OptError    ||Step||    CGits 
--------  --------------  ----------  ----------  ----------  -------
       0    5,269213e-01   0,000e+00
ERROR: LoadError: MethodError: no method matching eval_hesslag_prod(::Myquad, ::Array{Float64,1}, ::Array{Float64,1}, ::Float64, ::Array{Float64,1})
`

**Comment by sylvainmouret** [comment]
Hi Edouard,
Could you merge with the master and make sure everything is still OK (i.e. tests run fine)?
Thanks!

**Comment by sylvainmouret** [comment]
Replaced by #75 
Closing...

**Pull request closed without merging**
