### PR TITLE
[WIP] Switch to docs on gh-pages using Documenter

### LINKED ISSUE #56: documentation is dead
@yeesian, the docs seem to be broken: http://knitrojl.readthedocs.io/en/latest/knitro.html

### PR DESCRIPTION
**Pull request by yeesian**
closes #56

### CODE REVIEW

**Comment by yeesian** [comment]
> Pushing new commits to your master branch should trigger doc builds. Note that other branches do not trigger these builds and neither do pull requests by potential contributors.

([source](https://juliadocs.github.io/Documenter.jl/stable/man/hosting.html#Hosting-Documentation-1))

@mlubin this is ready for review. I'm mostly just guessing what the links are (e.g. in the README), but can only confirm after this branch gets merged, so it might require a second round of clean-up to fix broken links.

**Comment by mlubin** [comment]
Let's merge it and see how it looks. Won't do any harm since the current docs are broken anyway.

**Comment by mlubin** [comment]
(Merge when you're ready.)

**Comment by chriscoey** [comment]
@yeesian @mlubin were you guys generally happy with how Documenter.jl worked for these docs?

**Comment by yeesian** [comment]
Yeah I am. I wasn't using the advanced features in restructuredtext anyway, so the move to Documenter was straightforward, and smoother than I expected.

**Pull request merged**
