### PR TITLE
remove unneeded @docstrings line

### LINKED ISSUE #33: broken on julia master
```
julia> using KNITRO
WARNING: both Docile and Base export "@doc"; uses of it in module KNITRO must be qualified
ERROR: LoadError: UndefVarError: @doc not defined
 in include at ./boot.jl:254
 in include_from_node1 at ./loading.jl:197
 in require at ./loading.jl:146
while loading /home/mlubin/.julia/v0.4/KNITRO/src/KNITRO.jl, in expression starting on line 31
```

### PR DESCRIPTION
**Pull request by yeesian**
fixes #33

### CODE REVIEW

**Comment by mlubin** [comment]
Uh, this pull request was against the dead docstrings branch

**Comment by mlubin** [comment]
Fixed

**Comment by gragusa** [comment]
I was to submit a PR about this issue, but I just this. Any plan for tagging a release?

**Comment by yeesian** [comment]
Wanted to let the dust settle a little, in case there were any other problems. Does master work for you now?

**Comment by gragusa** [comment]
Master works perfectly on both 0.3 and 0.4

Giuseppe Ragusa

**Pull request merged**
