### PR TITLE
Fix warnings and added support for unconstrained problems

### PR DESCRIPTION
**Pull request by sylvainmouret**
I took over Huckl3b3rry87's pull request (c1387422) and udpated it.
Tests run OK on my machine although there are some warnings remaining, which I believe are not related to KNITRO specifically. I'd be glad if someone could review these at some point.
Also I kept support for Julia 0.5 although some additional warnings appear in this version.

### CODE REVIEW

**Comment by mlubin** [comment]
Looks good to me. What are the warnings that appear in 0.6 and/or 0.5?

**Comment by sylvainmouret** [comment]
Here are the warnings that I only see in 0.5 (there many others of similar type afterwards), do you see any problem with these?

WARNING: Method definition eval_f(Array{Float64, 1}) in module Main at C:\Users\XXX\.julia\v0.5\KNITRO\test\..\examples\hs015_tuner.jl:17 overwritten at C:\Users\XXX\.julia\v0.5\KNITRO\test\..\examples\hs035_nohess.jl:16.
WARNING: Method definition eval_g(Array{Float64, 1}, Array{Float64, 1}) in module Main at C:\Users\XXX\.julia\v0.5\KNITRO\test\..\examples\hs015_tuner.jl:22 overwritten at C:\Users\XXX\.julia\v0.5\KNITRO\test\..\examples\hs035_nohess.jl:22.
WARNING: Method definition eval_grad_f(Array{Float64, 1}, Array{Float64, 1}) in module Main at C:\Users\XXX\.julia\v0.5\KNITRO\test\..\examples\hs015_tuner.jl:27 overwritten at C:\Users\XXX\.julia\v0.5\KNITRO\test\..\examples\hs035_nohess.jl:26.
WARNING: Method definition eval_jac_g(Array{Float64, 1}, Array{Float64, 1}) in module Main at C:\Users\XXX\.julia\v0.5\KNITRO\test\..\examples\hs015_tuner.jl:33 overwritten at C:\Users\XXX\.julia\v0.5\KNITRO\test\..\examples\hs035_nohess.jl:32.

**Comment by mlubin** [comment]
That's not a big deal, just a small issue with how the tests are structured. You could put each test file in a separate module to avoid redefining the methods.

**Comment by sylvainmouret** [comment]
OK I'll leave as it is since the warnings do not appear in Julia 0.6.
Merging pull request...

**Pull request merged**
